export interface ErrorEntry {
  id: string;
  name: string;
  fqcn?: string;
  where: "broker" | "producer" | "consumer" | "admin" | "transactions" | "security";
  retriable: boolean;
  summary: string;
  cause: string;
  fix: string;
  learnSlug?: string;
  runbookSlug?: string;
}

export const errors: ErrorEntry[] = [
  {
    id: "not-enough-replicas-exception",
    name: "NotEnoughReplicasException",
    fqcn: "org.apache.kafka.common.errors.NotEnoughReplicasException",
    where: "producer",
    retriable: true,
    summary: "The broker rejected a produce request because the partition had fewer in-sync replicas than required by min.insync.replicas.",
    cause: "The producer is using acks=all and the ISR shrank below min.insync.replicas before the append. This is usually caused by follower lag, broker outages, replication throttling, or disk or network stalls on replicas.",
    fix: "Restore the ISR by fixing lagging or offline replicas before lowering durability guarantees. If the topic is intentionally under-replicated, increase the replication factor, add brokers, or revisit min.insync.replicas and producer acks together.",
    learnSlug: "isr-and-acks",
  },
  {
    id: "not-enough-replicas-after-append-exception",
    name: "NotEnoughReplicasAfterAppendException",
    fqcn: "org.apache.kafka.common.errors.NotEnoughReplicasAfterAppendException",
    where: "producer",
    retriable: true,
    summary: "The leader appended the batch locally, but not enough replicas acknowledged it before the produce response completed.",
    cause: "The append passed the pre-check, then the ISR changed or followers failed to replicate before the required acknowledgments arrived. The client cannot assume the write is committed even though the leader may have a local copy.",
    fix: "Retry with an idempotent producer so duplicate appends are fenced by sequence numbers. Investigate replica lag, throttles, and follower fetch latency; sustained occurrences mean the topic cannot satisfy its configured durability under current load.",
    learnSlug: "isr-and-acks",
  },
  {
    id: "offset-out-of-range-exception",
    name: "OffsetOutOfRangeException",
    fqcn: "org.apache.kafka.common.errors.OffsetOutOfRangeException",
    where: "consumer",
    retriable: false,
    summary: "A consumer requested an offset before the log start offset or after the current log end offset for a partition.",
    cause: "The committed offset may have expired due to retention, the topic may have been truncated after leader changes, or an operator may have reset offsets incorrectly. It can also happen when manually seeking to an offset from another cluster or generation.",
    fix: "Choose an explicit recovery policy: reset to earliest, latest, or a timestamp with kafka-consumer-groups or client logic. Audit retention, offset retention, and replication history so the group does not repeatedly commit offsets outside the retained log.",
  },
  {
    id: "unknown-topic-or-partition-exception",
    name: "UnknownTopicOrPartitionException",
    fqcn: "org.apache.kafka.common.errors.UnknownTopicOrPartitionException",
    where: "admin",
    retriable: true,
    summary: "A request referenced a topic or partition that the contacted broker does not currently know or host.",
    cause: "Metadata may be stale while a topic is being created or deleted, a partition is moving, or the client is talking to an old controller view. It also appears for misspelled topic names or when auto creation is disabled.",
    fix: "Refresh metadata and verify the topic exists with the expected partition count. For persistent failures, check controller logs, topic deletion state, ACL visibility, and whether the client bootstrap points at the right cluster.",
    learnSlug: "controller-and-metadata",
  },
  {
    id: "producer-fenced-exception",
    name: "ProducerFencedException",
    fqcn: "org.apache.kafka.common.errors.ProducerFencedException",
    where: "transactions",
    retriable: false,
    summary: "A transactional producer was fenced because another producer instance owns the same transactional.id with a newer epoch.",
    cause: "Kafka increments the producer epoch when a new instance initializes the same transactional ID. Any older instance that continues to send, commit, or abort is treated as a zombie and fenced to preserve exactly-once semantics.",
    fix: "Treat this as fatal for the producer instance: close it and let only the active owner continue. Ensure transactional.id values are stable per task shard but never shared by concurrently running instances.",
    learnSlug: "exactly-once",
  },
  {
    id: "invalid-producer-epoch-exception",
    name: "InvalidProducerEpochException",
    fqcn: "org.apache.kafka.common.errors.InvalidProducerEpochException",
    where: "transactions",
    retriable: false,
    summary: "The broker rejected a transactional or idempotent request because its producer epoch does not match broker state.",
    cause: "The producer is using an epoch older than the one stored by the transaction coordinator or partition state. This normally follows fencing, coordinator failover with state recovery, or a producer continuing after InitProducerId changed its epoch.",
    fix: "Do not retry the same producer blindly; close and recreate it through the normal transactional initialization path. For stream processors, verify task ownership and deployment orchestration so old instances stop before replacements write.",
    learnSlug: "exactly-once",
  },
  {
    id: "out-of-order-sequence-exception",
    name: "OutOfOrderSequenceException",
    fqcn: "org.apache.kafka.common.errors.OutOfOrderSequenceException",
    where: "producer",
    retriable: false,
    summary: "The broker observed a producer sequence number that was not the next expected sequence for that producer ID and partition.",
    cause: "Idempotent producers attach monotonically increasing sequence numbers per partition. Gaps or regressions can come from expired producer state, unsupported client configurations, retries after fatal errors, or multiple producers incorrectly sharing state.",
    fix: "With idempotence enabled, treat unexpected sequence errors as fatal unless the client library explicitly marks the transaction abortable. Keep enable.idempotence=true, avoid sharing producer instances across processes, and use modern clients with safe in-flight request handling.",
    learnSlug: "exactly-once",
  },
  {
    id: "record-too-large-exception",
    name: "RecordTooLargeException",
    fqcn: "org.apache.kafka.common.errors.RecordTooLargeException",
    where: "producer",
    retriable: false,
    summary: "A producer record or batch exceeded the client's configured send limit before or during produce.",
    cause: "The serialized record, headers, or compressed batch is larger than max.request.size or the effective batch limits in the producer. Large single records cannot be split by Kafka at the protocol layer.",
    fix: "Reduce payload size, store large blobs outside Kafka, or raise producer max.request.size in lockstep with broker and topic limits. Also review compression and batching: compression helps batches, but it does not make an oversized uncompressed record safe.",
  },
  {
    id: "message-size-too-large-exception",
    name: "MessageSizeTooLargeException",
    where: "broker",
    retriable: false,
    summary: "The broker rejected a produce request because the message batch exceeded broker or topic size limits.",
    cause: "This corresponds to Kafka's broker-side MESSAGE_TOO_LARGE path, commonly surfaced to Java clients as RecordTooLargeException. The batch is above message.max.bytes, max.message.bytes, or a replica and fetch limit needed for followers to replicate it.",
    fix: "Align topic max.message.bytes, broker message.max.bytes, replica.fetch.max.bytes, and consumer fetch limits before increasing producer max.request.size. Prefer reducing payloads; raising only one side creates records that can be accepted but not replicated or consumed.",
  },
  {
    id: "authorization-exception",
    name: "AuthorizationException",
    fqcn: "org.apache.kafka.common.errors.AuthorizationException",
    where: "security",
    retriable: false,
    summary: "A client operation failed because the authenticated principal lacks a required ACL.",
    cause: "The broker authorizer denied the request at cluster, topic, group, transactional ID, delegation token, or another resource scope. Generic AuthorizationException is often used when the failure is not tied to a narrower typed authorization exception.",
    fix: "Grant the least-privilege ACL required for the API key and resource, then retry with the same authenticated identity. Check listener security protocol mapping and principal builder output; many surprises are identity mismatches rather than missing ACLs.",
  },
  {
    id: "group-authorization-exception",
    name: "GroupAuthorizationException",
    fqcn: "org.apache.kafka.common.errors.GroupAuthorizationException",
    where: "security",
    retriable: false,
    summary: "The principal is not authorized to access the consumer group named in the request.",
    cause: "Group membership, offset commits or fetches, and group descriptions require permissions on the group resource. This often appears after changing group.id, using prefixed ACLs incorrectly, or running admin tooling with a service account that only has topic access.",
    fix: "Add READ or DESCRIBE permissions on the group as required by the operation, using a literal or prefixed ACL that matches the group.id. For transactional offset commits, also verify the producer's transactional ID permissions.",
    learnSlug: "consumer-rebalance",
  },
  {
    id: "topic-authorization-exception",
    name: "TopicAuthorizationException",
    fqcn: "org.apache.kafka.common.errors.TopicAuthorizationException",
    where: "security",
    retriable: false,
    summary: "The principal is not authorized for one or more topic resources in the request.",
    cause: "The operation requires topic ACLs such as READ, WRITE, DESCRIBE, CREATE, ALTER, or DELETE, and the authorizer denied at least one topic. Clients may report only a set of unauthorized topics, so mixed success across topics is possible.",
    fix: "Grant the operation-specific ACL on the exact topic or an intentional prefix, and include DESCRIBE where clients need metadata. Re-test with the same listener and SASL or SSL identity because ACLs are evaluated after authentication maps to a Kafka principal.",
  },
  {
    id: "timeout-exception",
    name: "TimeoutException",
    fqcn: "org.apache.kafka.common.errors.TimeoutException",
    where: "admin",
    retriable: true,
    summary: "The client or broker did not complete an operation within the configured deadline.",
    cause: "Timeouts are symptoms rather than root causes: metadata lookup, coordinator discovery, produce acknowledgments, fetches, and admin RPCs can all exceed request.timeout.ms or default.api.timeout.ms. Common triggers include unavailable leaders, overloaded brokers, network loss, or insufficient replication acknowledgments.",
    fix: "Inspect the operation-specific path before increasing timeouts. Fix leader or coordinator availability, broker saturation, DNS and network instability, or ISR health; then tune request.timeout.ms, delivery.timeout.ms, and default.api.timeout.ms to match realistic service times.",
  },
  {
    id: "invalid-replication-factor-exception",
    name: "InvalidReplicationFactorException",
    fqcn: "org.apache.kafka.common.errors.InvalidReplicationFactorException",
    where: "admin",
    retriable: false,
    summary: "A topic creation or reassignment request specified a replication factor the cluster cannot satisfy.",
    cause: "The requested replication factor is less than one or greater than the number of usable brokers, or it conflicts with rack-aware placement constraints. It also happens when defaults such as default.replication.factor are higher than broker count in small environments.",
    fix: "Add brokers or lower the requested replication factor or default for that environment. For production topics, prefer adding capacity over weakening replication, and validate rack labels before relying on rack-aware assignment.",
  },
  {
    id: "controller-moved-exception",
    name: "ControllerMovedException",
    fqcn: "org.apache.kafka.common.errors.ControllerMovedException",
    where: "admin",
    retriable: false,
    summary: "A controller-scoped request reached a broker that is no longer the active controller.",
    cause: "Controller leadership changed while the client or broker was sending a metadata-changing request. In KRaft and ZooKeeper modes alike, stale controller routing can happen during failover or controller quorum elections.",
    fix: "Retry after refreshing metadata so the request is sent to the current controller. If it is frequent, investigate controller churn, quorum health, GC pauses, and network partitions among controller nodes.",
    learnSlug: "controller-and-metadata",
  },
  {
    id: "not-leader-or-follower-exception",
    name: "NotLeaderOrFollowerException",
    fqcn: "org.apache.kafka.common.errors.NotLeaderOrFollowerException",
    where: "broker",
    retriable: true,
    summary: "The broker receiving the request is not the current leader or a valid follower for the partition.",
    cause: "Partition leadership or replica assignment changed and the client is using stale metadata. It can also arise during leader election, reassignment, broker restarts, or KRaft and ZooKeeper controller propagation delays.",
    fix: "Refresh metadata and retry; clients normally do this automatically for retriable operations. Persistent errors point to unstable leadership, offline replicas, bad advertised.listeners, or clients pinned to brokers that no longer host the partition.",
    learnSlug: "controller-and-metadata",
  },
  {
    id: "leader-not-available-exception",
    name: "LeaderNotAvailableException",
    fqcn: "org.apache.kafka.common.errors.LeaderNotAvailableException",
    where: "broker",
    retriable: true,
    summary: "A partition currently has no elected leader available to serve client requests.",
    cause: "The partition may be in leader election, all eligible replicas may be offline, or the controller has not propagated new metadata yet. Newly created topics can briefly report this before leaders are assigned.",
    fix: "Wait for metadata convergence for transient topic creation cases. For sustained incidents, restore an in-sync replica, resolve broker or controller failures, and avoid unclean leader election unless data-loss tradeoffs are explicitly accepted.",
    learnSlug: "unclean-leader-election",
  },
  {
    id: "kafka-storage-exception",
    name: "KafkaStorageException",
    fqcn: "org.apache.kafka.common.errors.KafkaStorageException",
    where: "broker",
    retriable: true,
    summary: "A broker hit a disk or log-directory failure while handling a request.",
    cause: "Kafka converts many post-startup log I/O failures into KafkaStorageException and marks the log directory offline. Clients are expected to refresh metadata because leadership may move away from the failed replica.",
    fix: "Treat this as a broker health incident: inspect disk errors, filesystem permissions, volume fullness, and log directory offline metrics. Replace or recover the failed storage, then let partition leadership and replicas rebalance before declaring the topic healthy.",
    learnSlug: "controller-and-metadata",
  },
  {
    id: "transactional-id-authorization-exception",
    name: "TransactionalIdAuthorizationException",
    fqcn: "org.apache.kafka.common.errors.TransactionalIdAuthorizationException",
    where: "security",
    retriable: false,
    summary: "The principal is not authorized to use the transactional.id in a transactional producer operation.",
    cause: "Transactions require ACLs on the transactional ID resource in addition to topic and group permissions. It appears during initTransactions, transaction commits or aborts, or transactional offset commits when the ID pattern is not granted.",
    fix: "Grant WRITE and DESCRIBE as needed on the transactional ID resource, usually with a prefixed ACL matching the application's transactional.id pattern. Keep the pattern narrow so unrelated applications cannot fence each other.",
    learnSlug: "exactly-once",
  },
  {
    id: "unsupported-version-exception",
    name: "UnsupportedVersionException",
    fqcn: "org.apache.kafka.common.errors.UnsupportedVersionException",
    where: "admin",
    retriable: false,
    summary: "The client attempted to use a Kafka protocol API version or feature that the broker does not support.",
    cause: "The client is newer than the broker, an API was sent to an older inter-broker protocol version, or a feature depends on finalized cluster feature levels not enabled yet. Mixed-version upgrades and old proxies commonly expose this.",
    fix: "Upgrade brokers or controllers, or configure the client to avoid the unsupported feature until the cluster is ready. During rolling upgrades, follow Kafka's documented order for binary upgrades, inter.broker.protocol.version or metadata.version changes, and client feature rollout.",
  },
];
