export interface KipEntry {
  id: number;
  title: string;
  status: "adopted" | "draft" | "wip" | "rejected";
  versionShipped?: string;
  plainSummary: string;
  why: string;
  learnSlug?: string;
  scenarioSlug?: string;
  kipUrl: string;
}

export const kips: KipEntry[] = [
  {
    id: 101,
    title: "Alter Replication Protocol to use Leader Epoch rather than High Watermark for Truncation",
    status: "adopted",
    versionShipped: "0.11.0.0",
    plainSummary: "KIP-101 added leader epochs to partition logs so replicas can reason about which leader wrote each range of offsets. Followers use epoch information rather than only high-watermark comparisons when truncating divergent logs after failover.",
    why: "It closed correctness gaps where a replica could keep records from an old leader and later rejoin with a divergent log.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-101+-+Alter+Replication+Protocol+to+use+Leader+Epoch+rather+than+High+Watermark+for+Truncation",
  },
  {
    id: 117,
    title: "Add a public AdminClient API for Kafka admin operations",
    status: "adopted",
    versionShipped: "0.11.0.0",
    plainSummary: "KIP-117 introduced the Java AdminClient as the supported programmatic API for administrative operations. It moved common cluster, topic, ACL, and configuration work away from shelling out to scripts or talking directly to ZooKeeper.",
    why: "Operators and platforms needed a stable client API for automation that worked through brokers and respected Kafka security.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-117%3A+Add+a+public+AdminClient+API+for+Kafka+admin+operations",
  },
  {
    id: 279,
    title: "Fix log divergence between leader and follower after fast leader fail over",
    status: "adopted",
    versionShipped: "2.0.0",
    plainSummary: "KIP-279 tightened the leader-epoch truncation protocol after cases where rapid leader changes could still leave followers with inconsistent logs. It refined how replicas discover the end offset for a leader epoch before deciding where to truncate.",
    why: "The goal was to preserve Kafka's no-divergence guarantee even when leadership changes faster than followers can fully reconcile.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-279%3A+Fix+log+divergence+between+leader+and+follower+after+fast+leader+fail+over",
  },
  {
    id: 320,
    title: "Allow fetchers to detect and handle log truncation",
    status: "adopted",
    versionShipped: "2.4.0",
    plainSummary: "KIP-320 made fetchers send the leader epoch they believe they are reading from and enabled brokers to detect stale or fenced epochs. Consumers and replica fetchers can then recover from truncation explicitly instead of silently reading from an invalid position.",
    why: "It made truncation after leader changes visible to clients and replicas, improving correctness around failover recovery.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-320%3A+Allow+fetchers+to+detect+and+handle+log+truncation",
  },
  {
    id: 345,
    title: "Introduce static membership protocol to reduce consumer rebalances",
    status: "adopted",
    versionShipped: "2.4.0",
    plainSummary: "KIP-345 added static group membership through group.instance.id. A restarted member can keep its identity across sessions, which lets the coordinator avoid unnecessary full rebalances for short bounces.",
    why: "Large stateful consumers and Kafka Streams apps needed restarts and rolling deploys to stop causing expensive partition movement.",
    learnSlug: "consumer-rebalance",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances",
  },
  {
    id: 405,
    title: "Kafka Tiered Storage",
    status: "adopted",
    versionShipped: "3.6.0",
    plainSummary: "KIP-405 defined Kafka's tiered storage architecture for moving older log segments to remote storage while brokers keep a smaller local hot set. It introduced broker-side remote log management concepts without changing the produce or consume APIs for normal clients.",
    why: "The feature reduces local disk pressure and makes retention, broker replacement, and partition movement less constrained by per-broker storage.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-405%3A+Kafka+Tiered+Storage",
  },
  {
    id: 429,
    title: "Kafka Consumer Incremental Rebalance Protocol",
    status: "adopted",
    versionShipped: "2.4.0",
    plainSummary: "KIP-429 introduced cooperative incremental rebalancing for consumers. Instead of revoking every partition on each membership change, assignors can move only the partitions that actually need to change owners.",
    why: "It reduced stop-the-world pauses and made rolling deploys less disruptive for consumers and Kafka Streams.",
    learnSlug: "consumer-rebalance",
    scenarioSlug: "rebalance-cooperative-classic",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol",
  },
  {
    id: 441,
    title: "Smooth Scaling Out for Kafka Streams",
    status: "adopted",
    versionShipped: "2.6.0",
    plainSummary: "KIP-441 improved Kafka Streams scaling by allowing new instances to warm up state before taking over active tasks. Standby and warmup replicas reduce the amount of state restoration that happens on the critical rebalance path.",
    why: "It made adding capacity to stateful Streams applications less likely to cause long processing pauses.",
    learnSlug: "partition-assignment",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-441%3A+Smooth+Scaling+Out+for+Kafka+Streams",
  },
  {
    id: 447,
    title: "Producer scalability for exactly once semantics",
    status: "adopted",
    versionShipped: "2.5.0",
    plainSummary: "KIP-447 changed the transaction protocol so a transactional producer could commit offsets with richer consumer group metadata. This removed important scaling limitations for exactly-once stream processing and was completed across broker, producer, and consumer changes.",
    why: "Exactly-once applications needed to scale and rebalance without tying transactional safety to overly rigid producer ownership patterns.",
    learnSlug: "exactly-once",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-447%3A+Producer+scalability+for+exactly+once+semantics",
  },
  {
    id: 462,
    title: "Use local thread id for KStreams",
    status: "adopted",
    versionShipped: "2.3.0",
    plainSummary: "KIP-462 changed Kafka Streams thread ID generation to use a counter local to each KafkaStreams instance. This keeps generated instance IDs stable when multiple Streams instances live in the same JVM.",
    why: "Stable local thread IDs preserve the benefits of static membership and avoid unnecessary rebalances after restarts.",
    learnSlug: "consumer-rebalance",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-462%3A+Use+local+thread+id+for+KStreams",
  },
  {
    id: 482,
    title: "The Kafka Protocol should Support Optional Tagged Fields",
    status: "adopted",
    versionShipped: "2.4.0",
    plainSummary: "KIP-482 added flexible protocol versions with optional tagged fields. New fields can be added to requests and responses in a forward-compatible way without forcing every intermediate version to understand them.",
    why: "Kafka needed safer protocol evolution as APIs grew and mixed-version clusters became more common.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-482%3A+The+Kafka+Protocol+should+Support+Optional+Tagged+Fields",
  },
  {
    id: 500,
    title: "Replace ZooKeeper with a Self-Managed Metadata Quorum",
    status: "adopted",
    plainSummary: "KIP-500 is the umbrella proposal for removing ZooKeeper from Kafka's metadata path. It moves cluster metadata into a Kafka-managed replicated log and controller quorum, later implemented through the KRaft line of KIPs.",
    why: "The project needed simpler operations, better scalability, and a controller architecture not bounded by ZooKeeper semantics.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum",
  },
  {
    id: 516,
    title: "Topic Identifiers & Topic Deletion State Improvements",
    status: "adopted",
    versionShipped: "2.8.0",
    plainSummary: "KIP-516 introduced stable topic IDs so the cluster can identify a topic independently from its mutable name. It also clarified topic deletion state to avoid clients and replicas confusing old and newly-created topics with the same name.",
    why: "Topic IDs make metadata, deletion, and recreation safer in large clusters and are foundational for KRaft metadata correctness.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-516%3A+Topic+Identifiers",
  },
  {
    id: 559,
    title: "Make the Kafka Protocol Friendlier with L7 Proxies",
    status: "adopted",
    versionShipped: "2.5.0",
    plainSummary: "KIP-559 made Kafka protocol messages more self-describing for layer-7 proxies. It focused on request and response fields whose byte payloads could not be interpreted without state from prior exchanges, especially group protocol metadata and assignments.",
    why: "Observable and policy-aware Kafka proxies need to parse requests independently without reverse-engineering client state.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-559%3A+Make+the+Kafka+Protocol+Friendlier+with+L7+Proxies",
  },
  {
    id: 580,
    title: "Exponential Backoff for Kafka Clients",
    status: "adopted",
    versionShipped: "3.7.0",
    plainSummary: "KIP-580 added retry.backoff.max.ms and exponential retry backoff with jitter across Kafka clients. Repeated failed requests back off progressively instead of hammering brokers at a fixed short interval.",
    why: "It reduces retry storms during broker failures, metadata convergence delays, and network incidents.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-580%3A+Exponential+Backoff+for+Kafka+Clients",
  },
  {
    id: 595,
    title: "A Raft Protocol for the Metadata Quorum",
    status: "adopted",
    versionShipped: "2.8.0",
    plainSummary: "KIP-595 specified the Raft-like protocol used by Kafka's metadata quorum. It adapts Kafka log replication concepts such as offsets and leader epochs to quorum commit semantics and controller elections.",
    why: "KRaft needed a consensus protocol for metadata that Kafka could operate internally without ZooKeeper.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-595%3A+A+Raft+Protocol+for+the+Metadata+Quorum",
  },
  {
    id: 630,
    title: "Kafka Raft Snapshot",
    status: "adopted",
    versionShipped: "3.0.0",
    plainSummary: "KIP-630 added snapshotting for the Kafka Raft metadata log. Controllers can compact metadata history into snapshots so new or recovering quorum members do not need to replay an unbounded log.",
    why: "Snapshots keep KRaft recovery time and metadata log size bounded as clusters live for years.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-630%3A+Kafka+Raft+Snapshot",
  },
  {
    id: 679,
    title: "Producer will enable the strongest delivery guarantee by default",
    status: "adopted",
    versionShipped: "3.0.0",
    plainSummary: "KIP-679 made idempotent production the default when producer settings are compatible with it. Producers therefore get stronger duplicate protection without every application explicitly setting enable.idempotence=true.",
    why: "The safe default reduced accidental at-least-once duplicates caused by retries in otherwise ordinary producer configurations.",
    learnSlug: "exactly-once",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-679%3A+Producer+will+enable+the+strongest+delivery+guarantee+by+default",
  },
  {
    id: 700,
    title: "Add Describe Cluster API",
    status: "adopted",
    versionShipped: "2.8.0",
    plainSummary: "KIP-700 added a dedicated DescribeCluster protocol API for AdminClient cluster metadata. AdminClient no longer has to overload the producer and consumer Metadata API to retrieve cluster ID, controller, broker list, and authorized operations.",
    why: "Administrative metadata needed its own extensible API surface without adding admin-only fields to the client metadata path.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-700%3A+Add+Describe+Cluster+API",
  },
  {
    id: 714,
    title: "Client metrics and observability",
    status: "adopted",
    versionShipped: "3.7.0",
    plainSummary: "KIP-714 introduced a client telemetry mechanism where brokers can subscribe clients to selected metrics and receive periodic client-side metric pushes. It gives cluster operators visibility into producer, consumer, and admin client behavior from the broker side.",
    why: "Kafka operations had a blind spot when client metrics stayed only inside applications or their local monitoring stacks.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-714%3A+Client+metrics+and+observability",
  },
  {
    id: 768,
    title: "Extend SASL/OAUTHBEARER with Support for OIDC",
    status: "adopted",
    versionShipped: "3.1.0",
    plainSummary: "KIP-768 extended Kafka's SASL/OAUTHBEARER support for OpenID Connect deployments. It added client and broker configuration for retrieving, validating, and refreshing OAuth tokens using standard OIDC provider metadata and JWKS endpoints.",
    why: "Kafka needed a production-grade OAuth path that integrated with common identity providers instead of only unsecured or custom token handling.",
    kipUrl: "https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=186877575",
  },
  {
    id: 848,
    title: "The Next Generation of the Consumer Rebalance Protocol",
    status: "adopted",
    versionShipped: "4.0.0",
    plainSummary: "KIP-848 redesigns consumer group rebalancing around a broker-side group coordinator protocol. Members heartbeat their subscriptions and receive incremental target assignments, removing the classic client-side leader assignment round.",
    why: "It lowers rebalance latency, improves coordinator control, and makes large groups less sensitive to slow or overloaded members.",
    learnSlug: "consumer-rebalance",
    scenarioSlug: "rebalance-consumer-protocol",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-848%3A+The+Next+Generation+of+the+Consumer+Rebalance+Protocol",
  },
  {
    id: 866,
    title: "ZooKeeper to KRaft Migration",
    status: "adopted",
    versionShipped: "3.4.0",
    plainSummary: "KIP-866 defined the migration path from ZooKeeper-based clusters to KRaft. It introduced a controlled migration mode so metadata can be copied and kept in sync while brokers and controllers transition roles.",
    why: "Operators needed an in-place path to KRaft that did not require rebuilding clusters or recreating topics from scratch.",
    learnSlug: "controller-and-metadata",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-866+ZooKeeper+to+KRaft+Migration",
  },
  {
    id: 877,
    title: "Mechanism for plugins and connectors to register metrics",
    status: "adopted",
    plainSummary:
      "KIP-877 defines Monitorable and PluginMetrics so Kafka plugins and Connect components can register metrics through the component that creates them, inheriting its namespace and identifying tags. The KIP names MirrorMaker 2 source and checkpoint connectors as affected Connect use cases.",
    why:
      "It makes plugin and connector metrics more consistently scoped and tagged, which matters when an operator maps MirrorMaker dashboards across version changes.",
    kipUrl:
      "https://cwiki.apache.org/confluence/spaces/KAFKA/pages/231116181/KIP-877+Mechanism+for+plugins+and+connectors+to+register+metrics",
  },
  {
    id: 878,
    title: "Autoscaling for Stateless & Statically Partitioned Streams",
    status: "adopted",
    plainSummary: "KIP-878 lets Kafka Streams expand internal topic partition counts when upstream input topics are expanded, for applications that are stateless or statically partitioned. It adds configuration and metrics so operators can enable and observe this autoscaling behavior.",
    why: "Streams applications needed a live scale-out path for partition-compatible topologies without stopping the app and manually repartitioning every internal topic.",
    learnSlug: "partition-assignment",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-878%3A+Internal+Topic+Autoscaling+for+Kafka+Streams",
  },
  {
    id: 890,
    title: "Transactions Server-Side Defense",
    status: "adopted",
    versionShipped: "3.7.0",
    plainSummary: "KIP-890 added broker-side defenses for transactions that can hang the last stable offset or admit delayed records into the wrong transaction. Newer protocol versions identify transactions more strongly by producer epoch and reduce reliance on explicit AddPartitionsToTxn calls.",
    why: "It protects exactly-once semantics against delayed requests, buggy clients, and transaction states that previously could stall read_committed consumers.",
    learnSlug: "exactly-once",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-890%3A+Transactions+Server-Side+Defense",
  },
  {
    id: 932,
    title: "Queues for Kafka (Share Groups)",
    status: "adopted",
    versionShipped: "4.2.0",
    plainSummary: "KIP-932 introduces share groups: a queue-like consumption model where many consumers cooperatively read from the same partitions and acknowledge individual records rather than owning exclusive partition ranges. Records are leased with an acquisition lock and can be accepted, released, or rejected independently; Kafka 4.2 made the feature production-ready.",
    why: "Classic consumer groups cap parallelism at the partition count and demand careful partitioning for fan-out work. Share groups let queue-like, per-record workloads — including AI agent tool-call and job-processing pipelines — scale consumers independently of partition count.",
    kipUrl: "https://cwiki.apache.org/confluence/display/KAFKA/KIP-932%3A+Queues+for+Kafka",
  },
  {
    id: 1066,
    title: "Mechanism to cordon brokers and log directories",
    status: "adopted",
    versionShipped: "4.3.0",
    plainSummary:
      "KIP-1066 adds cordoned log directories through the per-broker cordoned.log.dirs configuration. Cordoned directories continue serving existing replicas but are excluded from new partition and replica placement; cordoning every directory makes a broker ineligible for new placement.",
    why:
      "It gives operators a placement guardrail before disk or broker maintenance, scale-down, and capacity changes without pretending to evacuate existing replicas automatically.",
    kipUrl:
      "https://cwiki.apache.org/confluence/spaces/KAFKA/pages/311627566/KIP-1066+Mechanism+to+cordon+brokers+and+log+directories",
  },
];
